{
    "name": "CampScout Portal (Thin Client)",
    "version": "17.0.0.1.0",
    "category": "Tools/Camp Management",
    "summary": "Parent portal client — family dashboard, messaging, document signing",
    "description": "Portal UI integration and session tracking for parents",
    "author": "Fayna Digital",
    "website": "https://fayna.agency",
    "license": "LGPL-3",
    "depends": [
        "base",
        "website",
        "sale",
        "fayna_camp_template",
        "fayna_camp_qualification",
        "fayna_camp_stories",
    ],
    "data": ["views/campscout_views.xml"],
    "installable": True,
    "application": False,
}
